name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore RimHUD-Fix.sln

    - name: Build
      run: msbuild RimHUD-Fix.sln /p:Configuration=Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: RimHUD_Fix
        path: bin/Release/RimHUD_Fix.dll
